name: SupplySign
main: redsgreens.SupplySign.SupplySign
version: 1.10.0
author: redsgreens
api-version: 1.13
commands:
  supplysign:
    description: 'Used to reload data and list available SupplySign kits' 
    usage: '/supplysign <reload | listkits> (Used to reload data and list available SupplySign kits)'
website: http://dev.bukkit.org/server-mods/supplysign/
